### ISSUE TITLE
Initial volunteer user profile

### ISSUE THREAD

**Issue by dafeder** [ExperimentalFarmNetwork/efn-drupal#4]
## Story

As a volunteer, I want to easily submit all my profile information when I create a user account.

As an admin, I want all volunteers to submit required profile information.
## Acceptance Criteria
- Profile form contains all fields on [this google form](https://docs.google.com/forms/d/e/1FAIpQLSfDImmeZDgPskLOIrfKhwRxg1oh0yJgQNzEM-FUsWg5gBzCqg/viewform)

**Comment by farmernate** [comment]
It would be great to have an "add image to profile" option, in addition to the fields on the Google form.

**Comment by dafeder** [comment]
Many of the "other" fields don't make a lot of sense - for instance the land size one we see everything from 1 square foot to over 5 acres - what other options would we have? I think we should only allow "other" when absolutely necessary.

**Comment by farmernate** [comment]
That's fine. Whatever you think is best. I sometimes included "other"
options just to give people a chance to describe (say, if they have two
separate parcels 5 miles apart... A way to describe their land is
potentially useful, though that could go in the final "anything else" box,
or something). But I certainly recognize that makes searching more
challenging later if lots of people go with other instead of one of the
options.

Thanks!

**Comment by farmernate** [comment]
Excellent. I've been excited to watch you guys work... Though this was the
first github message I could actually understand...
Much appreciated. Let us know when/if we should meet up.
